version: "3"
services:
  jenkins:
    container_name: jenkins-server
    image: jenkins-lab:lts-jdk11
    build: jenkins/
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home